### ISSUE TITLE
SVG embedded no detected

### ISSUE THREAD

**Issue by jusore** [Douile/image-saver#1]
The option to download with Image Saver doesn't show.

The animated «on over» kitty (logo from GitHub) at the corner on this URL:

https://add0n.com/turbo-download-manager-v2.html?version=0.6.5&p=0.6.4&type=update

**Comment by Douile** [comment]
Right clicking in the other half of the square the SVG occupies works. But for some reason when you click over the visible (non-blank) section of the SVG the image doesn't register. Seems like an issue with the a element taking priority.
