### ISSUE TITLE
Appended number does not work in locations other than downloads

### ISSUE THREAD

**Issue by mattwright324** [Douile/image-saver#3]
When saving an image to a folder other than the usual downloads folder, a number is not appended (e.g. `(1)`, `(2)`) to the name automatically having to manually add one just like standard FireFox. 

For example, saving gifs out of https://giphy.com works as expected when downloading straight to Downloads but the number doesn't appear if I create a folder on my desktop and save multiple gifs to there instead.

**Comment by Douile** [comment]
Automatic renaming of files is not handled by this extension; there is no way for browser extension to detect names of files in the directory. This report is perhaps related https://bugzilla.mozilla.org/show_bug.cgi?id=687396
